// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zumyjlmcatmpwmlgeouq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bXlqbG1jYXRtcHdtbGdlb3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODA0MTgsImV4cCI6MjA2NjM1NjQxOH0.avxyCZHKFRpZo_4XHCmH06x5zxUxehaVGwLiIK4mc4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);